
import java.io.File;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.DefaultMutableTreeNode;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sudo
 */
public class crapau extends javax.swing.JFrame {

   /**
    * Creates new form crapau
    */
   public crapau() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel2 = new javax.swing.JPanel();
      BackGround = new javax.swing.JPanel();
      Side = new javax.swing.JPanel();
      Navigate = new javax.swing.JPanel();
      jLabel3 = new javax.swing.JLabel();
      Titre = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jScrollPane1 = new javax.swing.JScrollPane();
      jTree1 = new javax.swing.JTree();
      Filters = new javax.swing.JPanel();
      jLabel4 = new javax.swing.JLabel();
      Settings = new javax.swing.JPanel();
      jLabel5 = new javax.swing.JLabel();
      Galerie = new javax.swing.JPanel();
      Edit = new javax.swing.JPanel();

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 100, Short.MAX_VALUE)
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 100, Short.MAX_VALUE)
      );

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setAlwaysOnTop(true);
      setLocationByPlatform(true);
      setUndecorated(true);
      setPreferredSize(new java.awt.Dimension(922, 534));

      Side.setBackground(new java.awt.Color(53, 33, 89));
      Side.setName(""); // NOI18N

      Navigate.setBackground(new java.awt.Color(85, 65, 118));

      jLabel3.setForeground(new java.awt.Color(255, 255, 255));
      jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_opened_folder_25px_2.png"))); // NOI18N
      jLabel3.setText("Navigate");

      javax.swing.GroupLayout NavigateLayout = new javax.swing.GroupLayout(Navigate);
      Navigate.setLayout(NavigateLayout);
      NavigateLayout.setHorizontalGroup(
         NavigateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(NavigateLayout.createSequentialGroup()
            .addGap(71, 71, 71)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      NavigateLayout.setVerticalGroup(
         NavigateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
      );

      Titre.setBackground(new java.awt.Color(53, 33, 89));

      jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(255, 255, 255));
      jLabel1.setText("Crapauduc");

      jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      jLabel2.setForeground(new java.awt.Color(255, 255, 255));
      jLabel2.setText("Viewer");

      javax.swing.GroupLayout TitreLayout = new javax.swing.GroupLayout(Titre);
      Titre.setLayout(TitreLayout);
      TitreLayout.setHorizontalGroup(
         TitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(TitreLayout.createSequentialGroup()
            .addGap(61, 61, 61)
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel2)
            .addContainerGap(71, Short.MAX_VALUE))
      );
      TitreLayout.setVerticalGroup(
         TitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(TitreLayout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addGroup(TitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel1)
               .addComponent(jLabel2))
            .addContainerGap(20, Short.MAX_VALUE))
      );

      jTree1.setModel(new DefaultTreeModel(new DefaultMutableTreeNode(new File("C:\\Users\\Sudo\\Documents\\Crapauduc"))));
      jScrollPane1.setViewportView(jTree1);

      Filters.setBackground(new java.awt.Color(85, 65, 118));

      jLabel4.setForeground(new java.awt.Color(255, 255, 255));
      jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_filter_25px.png"))); // NOI18N
      jLabel4.setText("Filters");

      javax.swing.GroupLayout FiltersLayout = new javax.swing.GroupLayout(Filters);
      Filters.setLayout(FiltersLayout);
      FiltersLayout.setHorizontalGroup(
         FiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(FiltersLayout.createSequentialGroup()
            .addGap(71, 71, 71)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
      );
      FiltersLayout.setVerticalGroup(
         FiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
      );

      Settings.setBackground(new java.awt.Color(85, 65, 118));

      jLabel5.setForeground(new java.awt.Color(255, 255, 255));
      jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_settings_25px.png"))); // NOI18N
      jLabel5.setText("Settings");

      javax.swing.GroupLayout SettingsLayout = new javax.swing.GroupLayout(Settings);
      Settings.setLayout(SettingsLayout);
      SettingsLayout.setHorizontalGroup(
         SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(SettingsLayout.createSequentialGroup()
            .addGap(71, 71, 71)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
      );
      SettingsLayout.setVerticalGroup(
         SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
      );

      javax.swing.GroupLayout SideLayout = new javax.swing.GroupLayout(Side);
      Side.setLayout(SideLayout);
      SideLayout.setHorizontalGroup(
         SideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(Navigate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addGroup(SideLayout.createSequentialGroup()
            .addGap(72, 72, 72)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         .addComponent(Filters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addGroup(SideLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(Titre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
         .addComponent(Settings, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      SideLayout.setVerticalGroup(
         SideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(SideLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(Titre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(Navigate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(37, 37, 37)
            .addComponent(Filters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(29, 29, 29)
            .addComponent(Settings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      Galerie.setBackground(new java.awt.Color(122, 72, 221));

      javax.swing.GroupLayout GalerieLayout = new javax.swing.GroupLayout(Galerie);
      Galerie.setLayout(GalerieLayout);
      GalerieLayout.setHorizontalGroup(
         GalerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 614, Short.MAX_VALUE)
      );
      GalerieLayout.setVerticalGroup(
         GalerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 269, Short.MAX_VALUE)
      );

      javax.swing.GroupLayout EditLayout = new javax.swing.GroupLayout(Edit);
      Edit.setLayout(EditLayout);
      EditLayout.setHorizontalGroup(
         EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 0, Short.MAX_VALUE)
      );
      EditLayout.setVerticalGroup(
         EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 259, Short.MAX_VALUE)
      );

      javax.swing.GroupLayout BackGroundLayout = new javax.swing.GroupLayout(BackGround);
      BackGround.setLayout(BackGroundLayout);
      BackGroundLayout.setHorizontalGroup(
         BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(BackGroundLayout.createSequentialGroup()
            .addComponent(Side, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(Galerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(BackGroundLayout.createSequentialGroup()
                  .addGap(1, 1, 1)
                  .addComponent(Edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
      );
      BackGroundLayout.setVerticalGroup(
         BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
         .addComponent(Side, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addGroup(BackGroundLayout.createSequentialGroup()
            .addComponent(Galerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0)
            .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(crapau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(crapau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(crapau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(crapau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new crapau().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JPanel BackGround;
   private javax.swing.JPanel Edit;
   private javax.swing.JPanel Filters;
   private javax.swing.JPanel Galerie;
   private javax.swing.JPanel Navigate;
   private javax.swing.JPanel Settings;
   private javax.swing.JPanel Side;
   private javax.swing.JPanel Titre;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTree jTree1;
   // End of variables declaration//GEN-END:variables
}
