package GUI;


import Tag.Tag;

import java.awt.BorderLayout;

import javax.swing.JFrame;
import mdlaf.*;
import mdlaf.animation.*;
import javax.swing.*;
import java.awt.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Interface graphique du projet
 *
 * @author Groupe PRO B-9
 */
public class crapau extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = -8931841264030687778L;
        private final GUIRender GUIRender = new GUIRender();
	private Tag tagManager = new Tag();
   /**
    * Creates new form crapau
    */
   public crapau() {
      initComponents();
      jTreeManager1.setSlider(sliderDemo1);
      jTreeManager1.setTable(viewerTable);
      filtersPanel1.setManager(jTreeManager1);
      sliderDemo1.setTable(viewerTable);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        Side = new javax.swing.JPanel();
        Titre = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                ImageIcon m = new javax.swing.ImageIcon(getClass().getResource("/images/logo_allWhite.png"));
                Image i = m.getImage();

                g.drawImage(i,0,0, this.getSize().width, this.getSize().height, this);
            }

        };
        Filters = new javax.swing.JPanel();
        filters_label = new javax.swing.JLabel();
        Settings = new javax.swing.JPanel();
        settings_label = new javax.swing.JLabel();
        Navigate = new javax.swing.JPanel();
        Navigate_Titre = new javax.swing.JPanel();
        navigate_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTreeManager1 = new JTreeManager.JTreeManager();
        filtersPanel1 = new GUI.FiltersPanel();
        Galerie = new javax.swing.JPanel();
        play_button = new javax.swing.JButton();
        prev_button = new javax.swing.JButton();
        pause_button = new javax.swing.JButton();
        next_button = new javax.swing.JButton();
        sliderDemo1 = new GUI.SliderDemo();
        Edit = new javax.swing.JPanel();
        edit_label = new javax.swing.JLabel();
        tag_label = new javax.swing.JLabel();
        exit_button = new javax.swing.JButton();
        save_button = new javax.swing.JButton();
        reload_button = new javax.swing.JButton();
        undo_button = new javax.swing.JButton();
        add_row = new javax.swing.JButton();
        viewerTable = new GUI.ViewerTable();
        save_button1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CrapauducViewer");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(53, 33, 89));
        setIconImages(null);
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Side.setBackground(new java.awt.Color(53, 33, 89));
        Side.setName(""); // NOI18N

        Titre.setBackground(new java.awt.Color(53, 33, 89));

        javax.swing.GroupLayout TitreLayout = new javax.swing.GroupLayout(Titre);
        Titre.setLayout(TitreLayout);
        TitreLayout.setHorizontalGroup(
            TitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        TitreLayout.setVerticalGroup(
            TitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
        );

        Filters.setBackground(new java.awt.Color(85, 65, 118));

        filters_label.setForeground(new java.awt.Color(255, 255, 255));
        filters_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_filter_25px.png")));
        filters_label.setFont(GUIRender.getMainTitle());
        filters_label.setText("FILTERS");

        javax.swing.GroupLayout FiltersLayout = new javax.swing.GroupLayout(Filters);
        Filters.setLayout(FiltersLayout);
        FiltersLayout.setHorizontalGroup(
            FiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FiltersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filters_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        FiltersLayout.setVerticalGroup(
            FiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(filters_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        Settings.setBackground(new java.awt.Color(85, 65, 118));

        settings_label.setForeground(new java.awt.Color(255, 255, 255));
        settings_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_settings_25px.png")));
        settings_label.setFont(GUIRender.getMainTitle());
        settings_label.setText("STATISTICS");
        settings_label.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        settings_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settings_labelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SettingsLayout = new javax.swing.GroupLayout(Settings);
        Settings.setLayout(SettingsLayout);
        SettingsLayout.setHorizontalGroup(
            SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(settings_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        SettingsLayout.setVerticalGroup(
            SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(settings_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        Navigate.setBackground(GUIRender.getBackColor());

        Navigate_Titre.setBackground(new java.awt.Color(85, 65, 118));

        navigate_label.setForeground(new java.awt.Color(255, 255, 255));
        navigate_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_opened_folder_25px_2.png")));
        navigate_label.setFont(GUIRender.getMainTitle());
        navigate_label.setText("NAVIGATE");
        navigate_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navigate_labelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Navigate_TitreLayout = new javax.swing.GroupLayout(Navigate_Titre);
        Navigate_Titre.setLayout(Navigate_TitreLayout);
        Navigate_TitreLayout.setHorizontalGroup(
            Navigate_TitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Navigate_TitreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(navigate_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Navigate_TitreLayout.setVerticalGroup(
            Navigate_TitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navigate_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jTreeManager1);

        javax.swing.GroupLayout NavigateLayout = new javax.swing.GroupLayout(Navigate);
        Navigate.setLayout(NavigateLayout);
        NavigateLayout.setHorizontalGroup(
            NavigateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Navigate_Titre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(NavigateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );
        NavigateLayout.setVerticalGroup(
            NavigateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigateLayout.createSequentialGroup()
                .addComponent(Navigate_Titre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane1.getViewport().getView().setBackground(GUIRender.getBackColor());

        javax.swing.GroupLayout SideLayout = new javax.swing.GroupLayout(Side);
        Side.setLayout(SideLayout);
        SideLayout.setHorizontalGroup(
            SideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Filters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Settings, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Navigate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideLayout.createSequentialGroup()
                .addGroup(SideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SideLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(filtersPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Titre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        SideLayout.setVerticalGroup(
            SideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Navigate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Filters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(filtersPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(Settings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Galerie.setBackground(new java.awt.Color(122, 72, 221));

        play_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-play-24.png")));
        play_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                play_buttonActionPerformed(evt);
            }
        });

        prev_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-rewind-24.png")));
        prev_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prev_buttonActionPerformed(evt);
            }
        });

        pause_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-pause-24.png")));
        pause_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pause_buttonActionPerformed(evt);
            }
        });

        next_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-fast-forward-24.png")));
        next_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GalerieLayout = new javax.swing.GroupLayout(Galerie);
        Galerie.setLayout(GalerieLayout);
        GalerieLayout.setHorizontalGroup(
            GalerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GalerieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sliderDemo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GalerieLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(prev_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(play_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pause_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(next_button)
                .addGap(488, 488, 488))
        );
        GalerieLayout.setVerticalGroup(
            GalerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GalerieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sliderDemo1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GalerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(play_button)
                    .addComponent(prev_button)
                    .addComponent(next_button)
                    .addComponent(pause_button))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        edit_label.setText("Edit mode");

        tag_label.setText("Tag editor");

        exit_button.setText("Exit");
        exit_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_buttonMouseClicked(evt);
            }
        });
        exit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_buttonActionPerformed(evt);
            }
        });

        save_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-checkmark-24.png")));
        save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_buttonActionPerformed(evt);
            }
        });

        reload_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-restart-24.png")));
        reload_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reload_buttonActionPerformed(evt);
            }
        });

        undo_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-delete-24.png")));
        undo_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undo_buttonActionPerformed(evt);
            }
        });

        add_row.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-plus-24.png")));
        add_row.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_rowActionPerformed(evt);
            }
        });

        save_button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-sequence-24.png")));
        save_button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save_button1MouseClicked(evt);
            }
        });
        save_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EditLayout = new javax.swing.GroupLayout(Edit);
        Edit.setLayout(EditLayout);
        EditLayout.setHorizontalGroup(
            EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(EditLayout.createSequentialGroup()
                        .addComponent(save_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(save_button1))
                    .addComponent(tag_label)
                    .addComponent(edit_label))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditLayout.createSequentialGroup()
                        .addComponent(add_row)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(undo_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reload_button)
                        .addGap(929, 929, 929))
                    .addGroup(EditLayout.createSequentialGroup()
                        .addComponent(viewerTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit_button)
                .addGap(25, 25, 25))
        );
        EditLayout.setVerticalGroup(
            EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditLayout.createSequentialGroup()
                        .addComponent(edit_label)
                        .addGap(34, 34, 34)
                        .addComponent(tag_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(save_button)
                            .addComponent(save_button1))
                        .addGap(149, 149, 149)
                        .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add_row)
                            .addComponent(undo_button)
                            .addComponent(reload_button)))
                    .addComponent(viewerTable, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit_button))
        );

        javax.swing.GroupLayout BackGroundLayout = new javax.swing.GroupLayout(BackGround);
        BackGround.setLayout(BackGroundLayout);
        BackGroundLayout.setHorizontalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addComponent(Side, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Galerie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        BackGroundLayout.setVerticalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(Side, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addComponent(Galerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void navigate_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navigate_labelMouseClicked
      // TODO add your handling code here:
      //navigate_jtree.setVisible(false);
   }//GEN-LAST:event_navigate_labelMouseClicked

    private void play_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_play_buttonActionPerformed
        // TODO add your handling code here:
        sliderDemo1.startAnimation();
    }//GEN-LAST:event_play_buttonActionPerformed

    private void undo_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undo_buttonActionPerformed
        // TODO add your handling code here:
        viewerTable.delRow();
    }//GEN-LAST:event_undo_buttonActionPerformed

    private void reload_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reload_buttonActionPerformed
        // TODO add your handling code here:
        viewerTable.clear();
    }//GEN-LAST:event_reload_buttonActionPerformed

    private void exit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exit_buttonActionPerformed

    private void exit_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_buttonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit_buttonMouseClicked

    private void pause_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pause_buttonActionPerformed
        // TODO add your handling code here:
        sliderDemo1.stopAnimation();
    }//GEN-LAST:event_pause_buttonActionPerformed

    private void next_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_buttonActionPerformed
        // TODO add your handling code here:
        sliderDemo1.nextPicture();
    }//GEN-LAST:event_next_buttonActionPerformed

    private void add_rowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_rowActionPerformed
        // TODO add your handling code here:
        viewerTable.addRow();
    }//GEN-LAST:event_add_rowActionPerformed

    private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
        // TODO add your handling code here:
        if(sliderDemo1.getImage() != null){
            tagManager.saveTags(viewerTable.getData(), sliderDemo1.getImage());
        }
    }//GEN-LAST:event_save_buttonActionPerformed

    private void prev_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prev_buttonActionPerformed
        // TODO add your handling code here:
        sliderDemo1.prevPicture();
    }//GEN-LAST:event_prev_buttonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(JFrame.MAXIMIZED_BOTH); 
    }//GEN-LAST:event_formWindowOpened

    private void settings_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settings_labelMouseClicked
        new statisticsPage();
    }//GEN-LAST:event_settings_labelMouseClicked

    private void save_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_save_button1ActionPerformed

    private void save_button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_button1MouseClicked
        // TODO add your handling code here:
        if(sliderDemo1.getDirectory() != null){
            tagManager.saveTags(viewerTable.getData(), sliderDemo1.getDirectory());
        }
    }//GEN-LAST:event_save_button1MouseClicked

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
	UIManager.setLookAndFeel (new MaterialLookAndFeel ());
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(crapau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new crapau().setVisible(true);
         }
      });
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JPanel Edit;
    private javax.swing.JPanel Filters;
    private javax.swing.JPanel Galerie;
    private javax.swing.JPanel Navigate;
    private javax.swing.JPanel Navigate_Titre;
    private javax.swing.JPanel Settings;
    private javax.swing.JPanel Side;
    private javax.swing.JPanel Titre;
    private javax.swing.JButton add_row;
    private javax.swing.JLabel edit_label;
    private javax.swing.JButton exit_button;
    private GUI.FiltersPanel filtersPanel1;
    private javax.swing.JLabel filters_label;
    private javax.swing.JScrollPane jScrollPane1;
    private JTreeManager.JTreeManager jTreeManager1;
    private javax.swing.JLabel navigate_label;
    private javax.swing.JButton next_button;
    private javax.swing.JButton pause_button;
    private javax.swing.JButton play_button;
    private javax.swing.JButton prev_button;
    private javax.swing.JButton reload_button;
    private javax.swing.JButton save_button;
    private javax.swing.JButton save_button1;
    private javax.swing.JLabel settings_label;
    private GUI.SliderDemo sliderDemo1;
    private javax.swing.JLabel tag_label;
    private javax.swing.JButton undo_button;
    private GUI.ViewerTable viewerTable;
    // End of variables declaration//GEN-END:variables
}
